### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ghost** [codea-live/dclone#1]
![Screenshot 2021-09-17 5 39 00 PM](https://user-images.githubusercontent.com/75540107/133863334-93fec9eb-1496-47b1-b389-a05ce9b389d5.png)

> /home/runner/dclone-4/frontend/src/components/pages/guild-page.tsx
TypeScript error in /home/runner/dclone-4/frontend/src/components/pages/guild-page.tsx(31,18):
Type '{ children: Element[]; pageTitle: string; }' is not assignable to type 'IntrinsicAttributes & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement> & { ...; }'.
  Property 'pageTitle' does not exist on type 'IntrinsicAttributes & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement> & { ...; }'.  TS2322

>     29 |   
>     30 |   return (ui.activeGuild) ? (
>     31 |     <PageWrapper pageTitle={channel?.name ?? guild.name}>
>        |                  ^
>     32 |       <Sidebar />
>     33 |       {(channel)
>     34 |         ? <div className="bg-bg-primary">
>

**Comment by JayyDoesDev** [comment]
Steps to recreate?

**Comment by ghost** [comment]
> Steps to recreate?

ok i cd into frontend and i ran it with npm start then i went and cd into backend and started it but it showed error and both of the frontend and backend were running

**Comment by theADAMJR** [comment]
```
export type PageWrapperProps = React.DetailedHTMLProps<
  React.HTMLAttributes<HTMLDivElement>,
  HTMLDivElement> & { pageTitle?: string; };

// all separate pages should be wrapped by this
const PageWrapper: React.FunctionComponent<PageWrapperProps> = (props) => {
// ...
```
This is how the code should look like. If it always throws an error, it may have something to do with TypeScript or Webpack.

**Comment by ghost** [comment]
> ```
> export type PageWrapperProps = React.DetailedHTMLProps<
>   React.HTMLAttributes<HTMLDivElement>,
>   HTMLDivElement> & { pageTitle?: string; };
> 
> // all separate pages should be wrapped by this
> const PageWrapper: React.FunctionComponent<PageWrapperProps> = (props) => {
> // ...
> ```
> 
> This is how the code should look like. If it always throws an error, it may have something to do with TypeScript or Webpack.

thanks this helped alot
